2020-09-22 20:53:55,038 - ERROR - weibo.py[:1049] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1018, in get_pages
    self.print_user_info()
  File "weibo.py", line 540, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2020-09-22 20:53:55,043 - ERROR - weibo.py[:1093] - 'screen_name'
Traceback (most recent call last):
  File "weibo.py", line 1091, in start
    self.update_user_config_file(self.user_config_file_path)
  File "weibo.py", line 982, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'
2020-09-22 20:55:21,105 - ERROR - weibo.py[:1049] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1018, in get_pages
    self.print_user_info()
  File "weibo.py", line 540, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2020-09-22 20:55:21,108 - ERROR - weibo.py[:1093] - 'screen_name'
Traceback (most recent call last):
  File "weibo.py", line 1091, in start
    self.update_user_config_file(self.user_config_file_path)
  File "weibo.py", line 982, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'
2020-09-22 21:31:56,246 - ERROR - weibo.py[:1112] - 'id'
Traceback (most recent call last):
  File "D:/weibo-crawler/weibo.py", line 1103, in start
    logger.info("id("+user_config['id']+")为无效用户id！！！ " )
KeyError: 'id'
2020-09-22 21:32:07,286 - ERROR - weibo.py[:1112] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1103, in start
    logger.info("id("+user_config['id']+")为无效用户id！！！ " )
KeyError: 'id'
2020-09-22 21:32:48,631 - ERROR - weibo.py[:1139] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1137, in main
    wb.start()  # 爬取微博信息
  File "weibo.py", line 1103, in start
    logger.info("id("+user_config['id']+")为无效用户id！！！ " )
KeyError: 'id'
2020-09-23 10:25:49,580 - ERROR - weibo.py[:1062] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1031, in get_pages
    self.print_user_info()
  File "weibo.py", line 544, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2020-09-23 10:25:49,599 - ERROR - weibo.py[:1139] - 'screen_name'
Traceback (most recent call last):
  File "weibo.py", line 1137, in main
    wb.start()  # 爬取微博信息
  File "weibo.py", line 1110, in start
    self.update_user_config_file(self.user_config_file_path)
  File "weibo.py", line 986, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'
2020-09-23 10:27:30,316 - ERROR - weibo.py[:1062] - 'id'
Traceback (most recent call last):
  File "weibo.py", line 1031, in get_pages
    self.print_user_info()
  File "weibo.py", line 544, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
2020-09-23 10:27:30,318 - ERROR - weibo.py[:1140] - 'screen_name'
Traceback (most recent call last):
  File "weibo.py", line 1138, in main
    wb.start()  # 爬取微博信息
  File "weibo.py", line 1111, in start
    self.update_user_config_file(self.user_config_file_path)
  File "weibo.py", line 986, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'
